"""50 test queries for batch quality evaluation."""

TEST_QUERIES = [
    # ── 颜色 × 模板 (12) ──
    {
        "id": "color_01",
        "query": "做一个红色的恋爱纪念日卡片，纪念日是2024年6月1日",
        "expected_type": "anniversary",
        "expected_theme": "love",
        "expected_color": "红",
        "min_score": 70,
    },
    {
        "id": "color_02",
        "query": "蓝色的天气卡片",
        "expected_type": "weather",
        "expected_color": "蓝",
        "min_score": 70,
    },
    {
        "id": "color_03",
        "query": "紫色音乐播放器",
        "expected_type": "music",
        "expected_color": "紫",
        "min_score": 70,
    },
    {
        "id": "color_04",
        "query": "绿色的宝宝成长记录，2024年1月15日出生",
        "expected_type": "anniversary",
        "expected_theme": "baby",
        "expected_color": "绿",
        "min_score": 70,
    },
    {
        "id": "color_05",
        "query": "橙色闹钟提醒，每天早上7点",
        "expected_type": "alarm",
        "expected_color": "橙",
        "min_score": 70,
    },
    {
        "id": "color_06",
        "query": "粉色日历卡片",
        "expected_type": "calendar",
        "expected_color": "粉",
        "min_score": 70,
    },
    {
        "id": "color_07",
        "query": "黄色新闻资讯",
        "expected_type": "news",
        "expected_color": "黄",
        "min_score": 70,
    },
    {
        "id": "color_08",
        "query": "cyan colored weather widget",
        "expected_type": "weather",
        "expected_color": "cyan",
        "min_score": 65,
    },
    {
        "id": "color_09",
        "query": "做个#CC2244色的恋爱纪念",
        "expected_type": "anniversary",
        "expected_theme": "love",
        "expected_color": "#CC2244",
        "min_score": 65,
    },
    {
        "id": "color_10",
        "query": "放假倒计时，绿色风格，目标日期2026年10月1日",
        "expected_type": "anniversary",
        "expected_theme": "holiday",
        "expected_color": "绿",
        "min_score": 70,
    },
    {
        "id": "color_11",
        "query": "暖橙色纪念日卡片，2025-01-01开始",
        "expected_type": "anniversary",
        "expected_theme": "warm",
        "expected_color": "橙",
        "min_score": 70,
    },
    {
        "id": "color_12",
        "query": "红色闹钟 8:30",
        "expected_type": "alarm",
        "expected_color": "红",
        "min_score": 70,
    },

    # ── 视觉风格 (8) ──
    {
        "id": "style_01",
        "query": "极简风格的天气卡片",
        "expected_type": "weather",
        "expected_style": "minimal",
        "min_score": 70,
    },
    {
        "id": "style_02",
        "query": "像素风恋爱纪念日，2024-02-14",
        "expected_type": "anniversary",
        "expected_theme": "love",
        "expected_style": "pixel",
        "min_score": 65,
    },
    {
        "id": "style_03",
        "query": "material风格音乐播放器",
        "expected_type": "music",
        "expected_style": "material",
        "min_score": 70,
    },
    {
        "id": "style_04",
        "query": "毛玻璃风格日历",
        "expected_type": "calendar",
        "expected_style": "glass",
        "min_score": 70,
    },
    {
        "id": "style_05",
        "query": "pixel风格新闻",
        "expected_type": "news",
        "expected_style": "pixel",
        "min_score": 65,
    },
    {
        "id": "style_06",
        "query": "minimal alarm 6:00 AM",
        "expected_type": "alarm",
        "expected_style": "minimal",
        "min_score": 70,
    },
    {
        "id": "style_07",
        "query": "玻璃质感的宝宝成长，2025-03-01",
        "expected_type": "anniversary",
        "expected_theme": "baby",
        "expected_style": "glass",
        "min_score": 70,
    },
    {
        "id": "style_08",
        "query": "material design 放假倒计时 2026-05-01",
        "expected_type": "anniversary",
        "expected_theme": "holiday",
        "expected_style": "material",
        "min_score": 70,
    },

    # ── 文本压力测试 (10) ──
    {
        "id": "text_01",
        "query": "恋爱纪念日卡片，标题是「我和亲爱的小宝贝的超级浪漫甜蜜爱情纪念日快乐」，2024-01-01",
        "expected_type": "anniversary",
        "expected_theme": "love",
        "min_score": 60,
    },
    {
        "id": "text_02",
        "query": "宝宝成长记录，副标题是「每一天都是崭新的开始，宝贝你是我们最珍贵的礼物，愿你健康快乐地成长」，2024-06-15",
        "expected_type": "anniversary",
        "expected_theme": "baby",
        "min_score": 60,
    },
    {
        "id": "text_03",
        "query": "天气卡片，城市名是「中华人民共和国黑龙江省齐齐哈尔市」",
        "expected_type": "weather",
        "min_score": 60,
    },
    {
        "id": "text_04",
        "query": "音乐播放器，歌名「这是一首名字非常非常非常非常长的歌曲」，歌手「一个名字同样非常长的歌手」",
        "expected_type": "music",
        "min_score": 60,
    },
    {
        "id": "text_05",
        "query": "闹钟，标签「每周一三五的晨跑训练提醒闹钟别忘了带水壶」",
        "expected_type": "alarm",
        "min_score": 60,
    },
    {
        "id": "text_06",
        "query": "放假倒计时，标题「中华人民共和国国庆节七十五周年大庆」，2026-10-01",
        "expected_type": "anniversary",
        "expected_theme": "holiday",
        "min_score": 60,
    },
    {
        "id": "text_07",
        "query": "日历卡片，日程标题「与张三李四王五赵六在市中心国际会议中心B栋三楼会议室开会讨论季度规划」",
        "expected_type": "calendar",
        "min_score": 60,
    },
    {
        "id": "text_08",
        "query": "暖橙纪念日，副标题「这是一段用来测试超长文本截断效果的副标题文字，看看会不会溢出」，2023-12-25",
        "expected_type": "anniversary",
        "expected_theme": "warm",
        "min_score": 60,
    },
    {
        "id": "text_09",
        "query": "音乐播放器，歌词「Far across the distance and spaces between us, you have come to show you go on」",
        "expected_type": "music",
        "min_score": 60,
    },
    {
        "id": "text_10",
        "query": "天气卡片，建议穿搭「今天天气比较冷，建议穿羽绒服加围巾手套帽子全副武装出门注意保暖别感冒了」",
        "expected_type": "weather",
        "min_score": 60,
    },

    # ── 意图边界 (10) ──
    {
        "id": "intent_01",
        "query": "今天天气怎么样",
        "expected_type": "weather",
        "min_score": 65,
    },
    {
        "id": "intent_02",
        "query": "帮我设个早上七点半的闹钟",
        "expected_type": "alarm",
        "min_score": 70,
    },
    {
        "id": "intent_03",
        "query": "我和女朋友是2024年情人节在一起的",
        "expected_type": "anniversary",
        "expected_theme": "love",
        "min_score": 65,
    },
    {
        "id": "intent_04",
        "query": "宝宝上个月刚出生",
        "expected_type": "anniversary",
        "expected_theme": "baby",
        "min_score": 60,
    },
    {
        "id": "intent_05",
        "query": "放一首周杰伦的歌",
        "expected_type": "music",
        "min_score": 65,
    },
    {
        "id": "intent_06",
        "query": "看看今天有什么新闻",
        "expected_type": "news",
        "min_score": 65,
    },
    {
        "id": "intent_07",
        "query": "还有多久放暑假",
        "expected_type": "anniversary",
        "expected_theme": "holiday",
        "min_score": 60,
    },
    {
        "id": "intent_08",
        "query": "明天有什么安排",
        "expected_type": "calendar",
        "min_score": 60,
    },
    {
        "id": "intent_09",
        "query": "距离2026年圣诞节还有多少天",
        "expected_type": "anniversary",
        "expected_theme": "holiday",
        "min_score": 65,
    },
    {
        "id": "intent_10",
        "query": "做一个好看的卡片",
        "expected_type": None,  # any type is OK
        "min_score": 55,
    },

    # ── 三维组合 (5) ──
    {
        "id": "combo_01",
        "query": "红色像素风恋爱纪念日，2024-02-14",
        "expected_type": "anniversary",
        "expected_theme": "love",
        "expected_color": "红",
        "expected_style": "pixel",
        "min_score": 65,
    },
    {
        "id": "combo_02",
        "query": "蓝色极简天气",
        "expected_type": "weather",
        "expected_color": "蓝",
        "expected_style": "minimal",
        "min_score": 70,
    },
    {
        "id": "combo_03",
        "query": "紫色毛玻璃音乐播放器",
        "expected_type": "music",
        "expected_color": "紫",
        "expected_style": "glass",
        "min_score": 70,
    },
    {
        "id": "combo_04",
        "query": "绿色material日历",
        "expected_type": "calendar",
        "expected_color": "绿",
        "expected_style": "material",
        "min_score": 65,
    },
    {
        "id": "combo_05",
        "query": "橙色pixel风格闹钟 7:00",
        "expected_type": "alarm",
        "expected_color": "橙",
        "expected_style": "pixel",
        "min_score": 65,
    },

    # ── 向后兼容 (5) ──
    {
        "id": "compat_01",
        "query": "恋爱纪念日，2024-06-01",
        "expected_type": "anniversary",
        "expected_theme": "love",
        "min_score": 70,
    },
    {
        "id": "compat_02",
        "query": "天气",
        "expected_type": "weather",
        "min_score": 65,
    },
    {
        "id": "compat_03",
        "query": "闹钟 7:30",
        "expected_type": "alarm",
        "min_score": 70,
    },
    {
        "id": "compat_04",
        "query": "新闻",
        "expected_type": "news",
        "min_score": 65,
    },
    {
        "id": "compat_05",
        "query": "宝宝出生日2025-01-01",
        "expected_type": "anniversary",
        "expected_theme": "baby",
        "min_score": 70,
    },
]
